name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/users/deena-katma/projects/1
          github-token: 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
          labeled: bug, needs-triage
          label-operator: OR
          
